version: "3"

services:
  reverse-proxy:
    image: library/traefik:chevrotin
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./Docker/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./Docker/traefik/acme.json:/etc/traefik/acme.json
    networks:
      - backend
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
  dnsmasq:
    container_name: dnsmasq
    image: andyshinn/dnsmasq
    restart: always
    command: -A /local/127.0.0.1
    ports:
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:53:53/tcp"
    cap_add:
      - NET_ADMIN

networks:
  backend:
    internal: true
  frontend:
    external: true
    name: frontend